### ISSUE TITLE
[FE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/cashbook-7#10]
## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] Webpack
  - [ ] webpack-dev-server
- [ ] Typescript
- [ ] SCSS
- [ ] prettier
- [ ] SPA 라우팅, diff 계산

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- SPA를 위한 초기 세팅을 잘 해야합니다

## 🕙 예상 작업 기간

> 기능 구현에 예상되는 작업 기간

- 10시간

**Comment by crongro** [comment]
최소 작업단위는 2h를 넘지 않습니다.

**Comment by crongro** [comment]
최소 작업단위는 보통은 0.5MD

**Comment by KangyeolLee** [comment]
저도 롯데타워에서 일하고 싶습니다
